---
title: "Untitled"
author: "ses"
date: "1/27/2022"
output: html_document
---

```{r global-knitr-options, include=FALSE}
  knitr::opts_chunk$set(
  fig.pos = 'H',
  fig.asp = 0.618,
  fig.align='center',
  fig.width = 5,
  out.width = "100%",
  fig.cap = "", 
  fig.path = "chunk-img/",
  dpi = 300,
  # tidy = TRUE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")
```


```{r}
library(yaml)
library(tidyverse)
# library(pander)
#library(data.table)
# library(DT)
```


```{r}
modul_zsfg <- read_yaml("modul-zsfg.yaml")
```


```{r}
modul_zsfg[[1]]
```





```{r results='asis'}

titel <- modul_zsfg %>% names()

for (i in seq_along(titel)){
  
  this_title <- titel[i]
  cat("#", this_title, "\n")
  cat("\n")
  
  
  lernziele <- modul_zsfg[[i]][[1]]
  cat("## Lernziele \n")
  cat("\n")
  for (j in lernziele) {
    cat(paste0("- ", j))
    cat("\n")
  }
  
  cat("\n")
  cat("\n")
  
  
  literatur <- modul_zsfg[[i]][[2]]
  names_literatur <- names(literatur)
  cat("## Literatur \n\n")
  for (k in literatur) {
    chap <- literatur[[1]]
    cat(paste0("- ", names_literatur, ", Kap. ", chap))
    cat("\n")
  }
  
  cat("\n")
  cat("\n")
  
}
```

