---
title: "Hinweise zur Prüfungsleistung 'Vorhersagemodellierung'"
author: "Sebastian Sauer"
date: "`r Sys.time()`"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    number_sections: TRUE
editor_options: 
  chunk_output_type: console
lang: de-De
---


```{r global-knitr-options, include=FALSE}
  knitr::opts_chunk$set(
  fig.pos = 'H',
  fig.asp = 0.618,
  fig.align='center',
  fig.width = 5,
  out.width = "100%",
  fig.cap = "", 
  fig.path = "chunk-img/",
  dpi = 300,
  # tidy = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")
```

# Prüfungleistung

Prüfungsleistungen:

- Prognosewettbewerb (100%)



# Hinweise



```{r hinweise-prognosewettbewerb, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Hinweise/Prognosewettbewerb/Hinweise-Pruefung-Prognosewettbewerb-child.Rmd"
childtext <- readLines(url)
cat(childtext, sep="\n")
```





